### ISSUE TITLE
Using `!` as map key saves invalid YAML configuration

### ISSUE THREAD

**Issue by Prof-Bloodstone** [AuthMe/ConfigMe#134]
When saving YAML configuration, if a value of `"!"` is used as a Map key, it's not being quoted and results in:
```
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 29, column 10:
            $: EMERALD
             ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[patched_1.15.2.jar:git-Paper-329]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:468) ~[patched_1.15.2.jar:git-Paper-329]
	at dev.bloodstone.lib.configme.resource.YamlFileReader.loadFile(YamlFileReader.java:137) ~[?:?]
```

Lines 19-29 of generated config file:
```yaml
    # The shape player needs to put the ingredients in to craft the wand.
    # Needs to be a list of 1 to 3 rows, each with 1 to 3 ingredient placeholders.
    shape: 
    - $
    - $
    - '!'
    # Mapping between ingredient placeholder (used in shape), and ingredient type.
    # For possible values, see: https://papermc.io/javadocs/paper/1.15/org/bukkit/Material.html
    ingredients:
        !: STICK
        $: EMERALD
```
Notice that in `shape`, the exclamation mark is properly quoted.

Upon fixing line 28 to be:
```yaml
'!': STICK
```
Yaml parsers load the file sucessfully.

Not sure if it's bug in writing the file by ConfigMe or a bug in SnakeYaml itself.

**Comment by ljacqu** [comment]
Thanks a lot for the detailed bug report! It will be fixed with 1.2.0, which I intend to release this week.
